name: Rust

on:
  push:
    branches: [ shabbamm ]
  pull_request:
    branches: [ shabbamm ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
